workflows:
  ios-workflow:
    name: iOS Workflow
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Install Flutter dependencies
        script: |
          flutter pub get

      - name: Generate iOS Folder and Update Deployment Target
        script: |
          # Check if iOS folder exists, if not, create it
          if [ ! -d "ios" ]; then
            flutter create .
          fi

          # Navigate to the iOS directory
          cd ios

          # Ensure the Podfile exists and update the platform version
          echo "platform :ios, '13.0'" > Podfile

          # Add flutter dependencies and post install hook
          cat <<EOT >> Podfile
          flutter_application_path = '../'
          load File.join(flutter_application_path, 'packages', 'flutter_tools', 'bin', 'podhelper.rb')

          target 'Runner' do
            use_frameworks!
            flutter_install_all_flutter_pods(flutter_application_path)
          end
          EOT

          # Run pod install to install dependencies and create workspace
          pod install --repo-update

          # Go back to the root directory
          cd ..

      - name: Build iOS app
        script: |
          flutter build ios --release --no-codesign

    artifacts:
      - build/ios/ipa/*.ipa
