workflows:
  ios:
    name: iOS Build
    max_build_duration: 60
    scripts:
      # Step 1: Set up iOS environment and install Flutter dependencies
      - name: Set up Flutter environment
        script: |
          # Ensure Flutter is available and the environment is set up
          flutter doctor
          flutter pub get
          
          # Ensure that the iOS directory exists
          mkdir -p ios

          # Write the Podfile dynamically
          cat > ios/Podfile << EOF
          workspace 'Runner.xcworkspace'

          platform :ios, '13.0'

          # Correct Flutter application path
          flutter_application_path = '$PWD'
          load File.join(flutter_application_path, 'packages', 'flutter_tools', 'bin', 'podhelper.rb')

          flutter_install_all_ios_pods(flutter_application_path)
          EOF

      # Step 2: Install CocoaPods dependencies
      - name: Install CocoaPods dependencies
        script: |
          cd ios
          pod install

      # Step 3: Build iOS app
      - name: Build iOS app
        script: |
          flutter build ios --release --no-codesign
