workflows:
  ios:
    name: iOS Build
    max_build_duration: 60
    scripts:
      - name: Set up iOS environment
        script: |
          # Ensure that the iOS directory exists
          mkdir -p ios

          # Write the Podfile dynamically
          cat > ios/Podfile << EOF
          workspace 'Runner.xcworkspace'

          platform :ios, '13.0'

          flutter_application_path = '../'
          load File.join(flutter_application_path, 'packages', 'flutter_tools', 'bin', 'podhelper.rb')

          flutter_install_all_ios_pods(flutter_application_path)
          EOF

      - name: Install CocoaPods dependencies
        script: |
          # Install the pods
          cd ios
          pod install
          
      - name: Build iOS app
        script: |
          # Build the app (adjust as necessary)
          flutter build ios --release --no-codesign
