workflows:
  ios:
    name: iOS build and deploy
    max_build_duration: 60 # Max build time in minutes
    instances:
      - macos-latest
    environment:
      vars:
        FLUTTER_CHANNEL: stable
        FLUTTER_VERSION: 3.0.5 # Set the Flutter version you want
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
          flutter clean
      - name: Build iOS app
        script: |
          flutter build ios --release --no-codesign
    artifacts:
      - build/ios/iphoneos/*.ipa # The path to the IPA file (iOS app binary)
    publish:
      branches:
        - main # Only build when changes are pushed to the main branch
